spring:
  datasource:
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_batis?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Fan292852.
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml

dull:
  # 是否忽略表前缀
  table-prefix: true
  bean-query: Query
  path-base: D:/AResourceData/testResources/
  package-base: com.dullfan.CodeTest
  author: DullFan
  is-field-time-formatted: true
  field-ignore: id,status
  query-fuzzy: Fuzzy
  query-time-start: Start
  query-time-end: End