spring:
  datasource:
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/core?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Fan292852.
server:
  port: 9968
mybatis:
  mapper-locations: classpath:mapper/*.xml

dull:
  # 是否忽略表前缀
  table-prefix: false
  # 是否启动lombok
  lombok-enable: false
  # 输出路径
  path-base: D:/AStudyData/IdeaProjects/demo/src
  # 包名
  package-base: com.example.demo
  # 作者
  author: DullFan
  # 是否要忽略的字段
  field-ignore: id,status