spring:
  datasource:
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxxx?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: xxx
    password: xxxx
server:
  port: 9968
mybatis:
  mapper-locations: classpath:mapper/*.xml

dull:
  table-prefix: true
  bean-query: Query
#  path-base: /springboot/generate/
  path-base: D:/AResourceData/testResources/
  package-base: com.hahaha
  author: DullFan
  is-field-time-formatted: true
  field-ignore: id,status
  query-fuzzy: Fuzzy
  query-time-start: Start
  query-time-end: End